// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxxG2tNRRszIWuN76Q4yp9bKYnwTvjPYQ',
    appId: '1:168405382542:web:29b527f498c904be2aa0df',
    messagingSenderId: '168405382542',
    projectId: 'io-test-f158f',
    authDomain: 'io-test-f158f.firebaseapp.com',
    storageBucket: 'io-test-f158f.appspot.com',
    measurementId: 'G-J6L51Y5BVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_vXvdqAH4afgC6jZxJZAnBcxsYB8EAtg',
    appId: '1:168405382542:android:3fd1d7890233b7512aa0df',
    messagingSenderId: '168405382542',
    projectId: 'io-test-f158f',
    storageBucket: 'io-test-f158f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdzy3Y7jSe0M8GNJr_8yHtMBwg2hUPEoQ',
    appId: '1:168405382542:ios:5c14493ee2b3b9f72aa0df',
    messagingSenderId: '168405382542',
    projectId: 'io-test-f158f',
    storageBucket: 'io-test-f158f.appspot.com',
    iosClientId: '168405382542-don92ptun28lb9veiq1s0eir7qs8fagq.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdzy3Y7jSe0M8GNJr_8yHtMBwg2hUPEoQ',
    appId: '1:168405382542:ios:5c14493ee2b3b9f72aa0df',
    messagingSenderId: '168405382542',
    projectId: 'io-test-f158f',
    storageBucket: 'io-test-f158f.appspot.com',
    iosClientId: '168405382542-don92ptun28lb9veiq1s0eir7qs8fagq.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherapp',
  );
}
